# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Chris Pilcher'
tagline:          'Software Development'
url:              https://www.chrispilcher.com

author:
  name:           'Chris Pilcher'

paginate:         1

# Custom vars
ga_analytics:     UA-143287257-1